name: Etch and Mallet
favicon: null
layout_spectrum: 0.25148
typography_spectrum: 0.83965
title: Etch and Mallet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5b5650'
    - '#6c99b4'
    - '#000000'
    - '#fdd530'
    - '#bb871d'
  brandStrength: 0.08743748068809509
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
