name: Etch and Mallet
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52002
title: Etch and Mallet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#383838'
    - '#eaeaea'
    - '#a2a2a2'
    - '#696969'
    - '#cbcbcb'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
